### ISSUE TITLE
Loading Sentec data doesn't work 

### ISSUE THREAD

**Issue by wbaccinelli** [EIT-ALIVE/eitprocessing#191]
I tried to load Sentec files int his way:
```
file_data = load_eit_data(
    path_sentec,
    vendor="sentec",
    label="selected data",
)
```
but I get this error: 

Traceback (most recent call last):
  File "C:\Users\WalterBaccinelli\anaconda3\envs\eitprocessing\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-1ab836fd2f2c>", line 1, in <module>
    file_data = load_eit_data(
  File "C:\Users\WalterBaccinelli\Documents\EIT\eitprocessing\eitprocessing\datahandling\loading\__init__.py", line 75, in load_eit_data
    eit, continuous, sparse = load_func(
  File "C:\Users\WalterBaccinelli\Documents\EIT\eitprocessing\eitprocessing\datahandling\loading\sentec.py", line 92, in load_from_single_path
    fh.seek(payload_size, os.SEEK_CUR)
ValueError: seek out of range

**Comment by wbaccinelli** [comment]
@psomhorst do you have any idea of the cause?

**Comment by psomhorst** [comment]
@wbaccinelli Can you send met the hashes/file sizes of the *.zri files you have? I think we provided two Sentec data files, and I can load both without issue using the version in main.
